//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMangment.Domain.EmailOperations {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class EmailConfirmationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EmailConfirmationSettings defaultInstance = ((EmailConfirmationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EmailConfirmationSettings())));
        
        public static EmailConfirmationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://locis.lod-misis.ru/email/")]
        public string RouteToConfirmEmail {
            get {
                return ((string)(this["RouteToConfirmEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://locis.lod-misis.ru/password/")]
        public string RouteToRestorePassword {
            get {
                return ((string)(this["RouteToRestorePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://locis.lod-misis.ru/newEmail/")]
        public string RouteToChangeEmail {
            get {
                return ((string)(this["RouteToChangeEmail"]));
            }
        }
    }
}
